apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxinternal
spec:
  replicas: 1
  selector:
    matchLabels:
     app: nginxinternal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: nginxinternal
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: nginx
        image: <ACRUniquename>.azurecr.io/sample/nginx:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: nginxinternal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginxinternal
---
